---
apiVersion: v1
kind: Namespace
metadata:
  name: byedpi
  labels:
    app: byedpi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  byedpi
  namespace: byedpi
  labels:
    name:  byedpi
spec:    
  selector:
    matchLabels:
      app: byedpi
  template:
    metadata:
      labels:
        app: byedpi

    spec:
      containers:
      - image:  registry.home.local/byedpi:latest
        imagePullPolicy: Always
        name: byedpi

        resources:
          requests:
            cpu: 200m
            memory: 128M
          limits:
            memory: 256Mi
            cpu: 500m
        livenessProbe:
          tcpSocket:
            port: 1080
          initialDelaySeconds: 5
          timeoutSeconds: 10

        readinessProbe:
          tcpSocket:
            port: 1080
          initialDelaySeconds: 10
          timeoutSeconds: 10
          
        ports:
        - containerPort:  1080
          name:  byedpi
        command:
          - /opt/dpi/ciadpi
          - --hosts
          - /opt/dpi/hosts
          - -s1
          - -q1
          - -Y
          - -At
          - -f-1
          - -r1+s
          - -As
          - -o1

---
apiVersion: v1
kind: Service
metadata:
  name: byedpi-service-tcp
  namespace: byedpi
spec:
  selector:
    app: byedpi
  type: ClusterIP
  ports:
  - name: byedpi
    protocol: TCP
    port: 1080
    targetPort: 1080

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: byedpi-ingress-route-tcp
  namespace: byedpi
spec:
  entryPoints: [byedpi]
  routes:
    - match: HostSNI(`*`)
      services:
        - name: byedpi-service-tcp
          port: 1080
